### PR TITLE
Add contributor community and core.

### PR DESCRIPTION
**Pull request by nanliu**

### CODE REVIEW

**Comment by kindermoumoute** [comment]
When `@configs['maintainer'] == 'community'`, does this mean the repo is still hosted in intelsdi-x?
If no this line should update the githubID: https://github.com/nanliu/snap-pluginsync/blame/maintainers/moduleroot/CONTRIBUTING.md#L18

**Comment by nanliu** [comment]
At the moment it will still be in the intelsdi-x repo, and we will have both core/community plugins.

**Comment by kindermoumoute** [comment]
Ok, LGTM.

**Comment by nanliu** [comment]
Somehow git lost track of the repo. Rebased PR and will merge #23 instead.

**Pull request closed without merging**
